DROP DATABASE IF EXISTS Fresher;
CREATE DATABASE Fresher;
USE Fresher;

DROP TABLE IF EXISTS Trainee;
CREATE TABLE Trainee(
	Trainee_id INT AUTO_INCREMENT PRIMARY KEY,
	Full_name VARCHAR(25) NOT NULL,
	Birth_Date DATE NOT NULL,
	Gender ENUM('male','Female') NULL,
	ET_IQ  TINYINT CHECK(ET_IQ >=0 && ET_IQ < 20),
	-- ET-E : ET-ENGLISH
	ET_E TINYINT CHECK(ET_E >=0 && ET_E < 20),
	-- ET-G : ET-GMATH
	ET_G TINYINT CHECK(ET_G >=0 && ET_G <50),
	Tranining_class  VARCHAR(50) NOT NULL,
	Evaluation_note  VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS DEV;
CREATE TABLE DEV(
	ID		 TINYINT AUTO_INCREMENT PRIMARY KEY,
	FULLNAME	VARCHAR(50) NOT NULL,
	`Code`  VARCHAR(5) NOT NULL,
	ModifiedDate DATETIME
);

DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM(
	ID		 TINYINT AUTO_INCREMENT PRIMARY KEY,
	FULLNAME	VARCHAR(50) NOT NULL,
	BirthDate DATE NOT NULL,
	Gender ENUM('male','Female') NULL,
	IsDeletedFlag ENUM('dang hoat dong','da xoa') NOT NULL
);








